### PR TITLE
Iss106

### PR DESCRIPTION
**Pull request by mholtrop**
This replaces the optparse with argparse with minimal modifications of the code behavior.
All the _cfg.py files are modified to the changes in baseConfig.py, and also made Python3 compatible.

The only significant change in behavior is that now the -i option can be given multiple files, referring forward to Omar's future work to permit multiple input files.

In a _cfg.py script, the main changes required are:

* Parser just returns the options, and no args. If needed positional parameters can be added to the parameter list.
(options, args) = parser.parse_args()  => options = parser.parse_args()
* infiles returned by the -i is now a list, so the [] are no longer needed.
p.input_files = [infiles]  => p.input_files = infiles
* Additional options need add_argument() instead of add_option()
* For added options, the type="string" needs to be replaced by type=str and similar for other data types.

### CODE REVIEW

**Review by omar-moreno — APPROVED** [review]
This is a minor change so it's fine.

**Comment by omar-moreno** [comment]
Going forward, we will likely want to do some major cleanup of the python modules.  For example, instead of having a config for every single processor, we can simply just have functions with some reasonable defaults that people can call within their own config. Also, we should follow a doc convention (e.g. numpy) and use something like sphinx to automatically generate docs.

**Comment by mholtrop** [comment]
@omar-moreno I don't disagree with what you are saying. My preference would be to have all defaults for a config be defaults in the processor class. I think this is largely the case already, and many of the processors can be added without setting any additional configurations.

**Comment by cbravo135** [comment]
We don't have a config for every single processor, that statement is blatantly false. There are costs as well as benefits to hiding this kind of stuff away via an import. We should be careful about this, as it tends to result in having end users being unaware of what they are actually running. I want hpstr to at least a little "difficult" because that difficultly will force people to be more aware of what they are running. I brought up early on trying to force people to make their own config as @omar-moreno is suggesting now, and was met with serious resistance. We want a package that can be used effectively by people of all skill level, and catering to either power users or the complete newbie will detract from this goal. the cfg.py files are not any where close to being unmanageable at this time, the longest one being only about 100 lines. Maurik is also right that we have made an effort to put defaults into the processors which won't require they are configured. processors/config/*cfg.py though are meant for testing purposes as well as providing examples of what is available in each processor to be configured. I don't really see this ever becoming a serious issue on hps though, given the scale of the experiment.

**Comment by cbravo135** [comment]
This shouldn't go in yet, as it doesn't update all the cfg files since merging in the latest bump hunt code from Kyle. Sorry about merging that before this @mholtrop, can you update those new scripts. After we merge this, we can start requiring new stuff added going forward to follow these new conventions.

**Comment by mholtrop** [comment]
No problem. Fixed up the py file from Kyle's pull.

**Pull request merged**
