### PR TITLE
make hpstr work with C++17 standard

### PR DESCRIPTION
**Pull request by sarahgaiser**
I installed hpstr with C++17 standard and these are the changes I had to make for it to compile.

### CODE REVIEW

**Review by cbravo135 — APPROVED** [review]
Thanks!

**Comment by sarahgaiser** [comment]
Can you double-check that `std::vector<float [12]> baselines` is not needed? at a first glance it seemed to be but I am not 100% sure

**Comment by cbravo135** [comment]
I did when I first approved it, but I think we want to hold off on merging this until we get a version of ROOT on s3df and ifarm which are built up to C++17 so this will compile at those two sites.

**Review by cbravo135 — CHANGES_REQUESTED** [review]
Taking away approval until s3df and ifarm systems are ready.

**Comment by tomeichlersmith** [comment]
Any update the build @cbravo135 ? I've been using C++17 for a bit and would like to avoid having to carry these changes around on my branches...

**Review by cbravo135 — APPROVED** [review]

**Pull request merged**
