### PR TITLE
Iss92 - Add LCIO ID to TrackerHit and stores the collection of MCParticles in a map

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by omar-moreno** [comment]
I still need to any analyses or processors that use the collection of MCParticles.

**Comment by omar-moreno** [comment]
Resolves #92

**Review by mholtrop — APPROVED** [review]
These changes will need a bit of explanation, especially making a Map for MCParticle, which breaks compatibility with v1 root files. For a root file created with the previous version of hpstr, you can no longer load it:
`root [15] t1->SetBranchAddress("MCParticle", &mcparts, &mcpart_br)
Error in <TTree::SetBranchAddress>: The class requested (vector<MCParticle*>) for the branch "MCParticle" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (vector<MCParticle*>) to avoid to write corrupted data.`

At this point, that is probably okay, since we haven't created a lot of root files for MC, and re-create them if needed. 

It may be useful for newer programmers to have an example how the MCParticle is now getting accessed.  Better yet, resurrect some "Event" class that does some of the heavy lifting for you.

I approve this, but we should have a general discussion soon on event model, and format.

**Review by cbravo135 — CHANGES_REQUESTED** [review]
Overall, this pretty clearly is gonna break VertexAnaProcessor, at the very least. I am thinking more stuff will need to be updated to fully make these changes proposed here. We should discuss how we can improve how we deal with matching to MC particles, but it A solution to this is already in VertexAnaProcessor. 

All that being said, this fails to compile from scratch as is, so before we can test the other parts of the code this could break, we should first get it to compile.

```[ 30%] Linking CXX shared library libevent.so
/usr/bin/ld: CMakeFiles/EventDict.dir/EventDict.cxx.o: in function `CalCluster::Dictionary()':
EventDict.cxx:(.text+0x4bd0): multiple definition of `CalCluster::Dictionary()'; CMakeFiles/event.dir/EventDict.cxx.o:EventDict.cxx:(.text+0x4bd0): first defined here
/usr/bin/ld: CMakeFiles/EventDict.dir/EventDict.cxx.o:(.bss+0x70): multiple definition of `CalCluster::fgIsA'; CMakeFiles/event.dir/EventDict.cxx.o:(.bss+0x70): first defined here
/usr/bin/ld: CMakeFiles/EventDict.dir/EventDict.cxx.o: in function `CalHit::Dictionary()':
EventDict.cxx:(.text+0x4d80): multiple definition of `CalHit::Dictionary()'; CMakeFiles/event.dir/EventDict.cxx.o:EventDict.cxx:(.text+0x4d80): first defined here
/usr/bin/ld: CMakeFiles/EventDict.dir/EventDict.cxx.o:(.bss+0x68): multiple definition of `CalHit::fgIsA'; CMakeFiles/event.dir/EventDict.cxx.o:(.bss+0x68): first defined here
/usr/bin/ld: CMakeFiles/EventDict.dir/EventDict.cxx.o: in function `EventHeader::Dictionary()':
EventDict.cxx:(.text+0x4f30): multiple definition of `EventHeader::Dictionary()'; CMakeFiles/event.dir/EventDict.cxx.o:EventDict.cxx:(.text+0x4f30): first defined here
/usr/bin/ld: CMakeFiles/EventDict.dir/EventDict.cxx.o:(.bss+0x60): multiple definition of `EventHeader::fgIsA'; CMakeFiles/event.dir/EventDict.cxx.o:(.bss+0x60): first defined here
...
```

**Comment by omar-moreno** [comment]
@cbravo135 Not sure what the error is all about. I have compiled on rhel6 and opensuse without issue. Seems like @mholtrop had no issue either.  Maybe you need to start with a clean build.

**Comment by omar-moreno** [comment]
I looked at how things were done in VertexAnaProcessor but this solution allows MC processing to be done across all processors in a more generic way and allows a reference to the MC particle from any class without having to save a reference.  I'm happy to update VertexAnaProcessor.  @pbutti you have any issue with this?

**Comment by cbravo135** [comment]
I did build it completely from scratch and got these errors. These errors are happening when libevent is being linked. I am building on Ubuntu 20.04 using GNU 8.4.0.

**Comment by cbravo135** [comment]
This solution does also seem to be a second work around while we don't have a transient though. Do we really need to change the work around rather than just adding the transient? Switching to a map to hold MCParticles, rather than a vector, makes studying them directly from the ntuple using TTree Draw more difficult. Why only keep MCParticles in a map? Sure it is slower to loop over them all to find the one you want. In the end all of this is just a fancier hack, and we should just fix the issue at its core by adding a transient.

**Comment by cbravo135** [comment]
The benefit of this solution is it saves time from having to loop over the vector to find the one you want. I don't think we can claim "this solution allows MC processing to be done across all processors in a more generic way". The two solutions are pretty much identical, this one just saves some time by being able to directly get the reference via a map rather than looping over everything in the vector. Why keep only MCParticles in a map and everything else in a vector? If we put in the transient we could just have a direct reference kept in the object that it is related to. This seems like the "correct" solution to me, neither this PR or what we already have are "correct". How is this not just a slightly more sophisticated work around?

**Comment by omar-moreno** [comment]
@cbravo135 Can you provide an example of how I can use the MCParticle matching in VertexAna in the processor FindableTrackProcessor? Is there a method I can call that will match hits to MCParticles? 

Having a map simplifies this quite a bit by allowing me to simply tag a hit with the unique LCIO ID that is associated with an MCParticle.  I can then access the MCParticle directly as you point out above. 

Even with the collections being transient, you still need a way to match an object to its MCParticle. This allows us to easily do that.  Also, this doesn't require a user to write their own "matching code" as it's simply accessing a map by a key.

**Comment by mholtrop** [comment]
About compiling the code:

The code compiles fine on MacOS 10.15.5 and on Ubuntu 20.04 (in Docker image).
However, I did need to pull in master to avoid an issue that I think was unrelated to the code changes on iss92. I just pushed the merge with master onto iss92 and will do the same for iss90.

About using the root file:

I found that I can load the root tree and I can use it within the TBrowser (i.e. click on a leaf) without problems. 
I can also "just draw" the MCParticle content from the tree:

root [0] R__LOAD_LIBRARY(cbuildu/lib/libevent)
root [1] TFile f("mc_pulse_2019.root")
(TFile &) Name: mc_pulse_2019.root Title: 
root [2] TBrowser b;
root [3] auto tree = (TTree *)f.Get("HPS_Event")
(TTree *) @0x7ffea7b24320
root [4] tree->Draw("MCParticle.pz_")
root [5] 

So, I kind of don't see any of the issues here?

**Comment by cbravo135** [comment]
"Having a map simplifies this quite a bit by allowing me to simply tag a hit with the unique LCIO ID that is associated with an MCParticle." This doesn't simplify anything, and is exactly what was already being done, we just didn't have the lcio ids saved in the MCTrackerHits before. The issue still exists that this breaks VertexAnaProcessor. I honestly don't care which way it is done, this way will be a bit faster is all. Let's not act like this is more than merely changing the MCParticle container to avoid looping over the vector to find the correct one via the lcio id saved in the referencing object. I am okay with doing this, but would like ALL the code that uses an MCParticle collection to be updated.

**Comment by cbravo135** [comment]
Pulling from master fixed my build issue, btw.

**Comment by cbravo135** [comment]
"Truth matching" in analysis is a subtle issue which tends to have analysis specific reasoning behind how you define your "match". Asking for a general purpose tool to do truth matching in general feels like an attempt to sweep the deep analysis issues behind truth matching MC in the grand scheme "under the rug". The specific issues totally make sense to be addressed at the AnaProcessor level. The way I truth match the PDGID 622 particle to be the mother of the electron matched to the most hits on the track is pretty specific to the radiative fraction portion of our analysis, and I don't see where we would ever want to do exactly this outside of the context which we are trying to cover with VertexAnaProcessor.

"Can you provide an example of how I can use the MCParticle matching in VertexAna in the processor FindableTrackProcessor?" 
Yes, and I already did point you to an example of how this can be done in VertexAnaProcessor. Clearly there isn't "a method I can call that will match hits to MCParticles?" If you have the lcio id info in the MCTrackerHit objects, then you can easily get the correct MCParticle. This is so little and so simple code, I don't really see having an explicit method to do it. Using the map, the method would literally just return the key lookup. I don't care if it is sped up via a map like you have done or not, but your request for a generic method is ambiguously impossible to implement. The exact kind of matching you are doing now hasn't been done before though, so why would there be any expectation of support for it?

Looking further into the future, we will continue to increase the number of types of matching we are using to validate and study our MC. Having a separate dedicated tool for each type of matching will run very similar code multiple times and it is cleaner for these just to live in the analysis processors themselves, that way the same set of loops can perform every type of match we may want in that particular processor. It also makes it easier to integrate matching into the region definitions and make plots to validate the behavior of our matching algorithms.

**Comment by omar-moreno** [comment]
If you are going to create a set of tools, shouldn't those live in
hps-java?

**Comment by cbravo135** [comment]
The tools which link the relationship between objects in LCIO does already exist. The question is how does hpstr handle these and make a more end user friendly environment to access them? Not sure what your point is, don't these tools already exist in hps-java, which produce the LCRelation objects we are reading in?

Not sure you understood my point. Building up the logic needed to define analysis regions for MC needs to happen in the AnaProcessor. Anything we add to hps-java that we want to use for analysis will necessarily have to have some code added to hpstr somehow. We have to have some way of accessing the truth information at this level to be capable of performing our physics analysis. Adding tons of LCRelations for all possible combos of "matching" we want to do would be ridiculous. Enough information is already available in the LCIO files to abstractly match however we may decide we want to. MC event categorization is an analysis question, not really something we need to worry about at the reconstruction level.

**Comment by omar-moreno** [comment]
Closing this for now and will reevaluate if needed in the future.

**Pull request closed without merging**
