### PR TITLE
Make Python3 compatible.

### PR DESCRIPTION
**Pull request by mholtrop**
Fixed a bug in ConfigurePython where the argument count was incorrect.
Fixed a bug in ConfigurePython where the script was loaded outside of the try{} catch. 
Moved the executable code outside of the libraries.
Made changes to ConfigurePython so that it is now Python3 compatible.

Tested with Python2 and Python3.

### CODE REVIEW

**Comment by omar-moreno** [comment]
Why move everything into an execs folder?

**Comment by mholtrop** [comment]
Maybe I am too OCD. 
Seemed just wrong to have a "main" in a library, and I did not see a way around that without doing major retooling on the MacroModule.cmake. 
The ConfigurePython is also only needed for the hpstr executable, so I moved that too.

**Comment by omar-moreno** [comment]
OK, not sure that justifies the change.  I recommend moving things back to
keep this PR minimal.  We can discuss changes like this at the software
meeting.

**Comment by mholtrop** [comment]
OK done. Moved it back. 
Still seems wrong :-)

**Comment by omar-moreno** [comment]
Thanks :)

**Comment by cbravo135** [comment]
I agree with Omar, we should discuss with everyone in the software meeting before we merge this.

**Comment by cbravo135** [comment]
Checked out this branch and resolved the merge conflict in Process.cxx, and successfully compiled using python 2.7. At runtime, I am getting a segmentation violation during the python configuration step.
```
bravo@cbravo-hps:~/src/hpstr/run/sims$ hpstr mcTuple_cfg.py muonHpsSim.slcio 
mcTuple_cfg.py
---- [ hpstr ]: Loading configuration --------

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fd8a012207a in __GI___waitpid (pid=16990, stat_loc=stat_loc
entry=0x7fff4d2ef480, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007fd8a009afbb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007fd8a0f59c0d in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x202e570) at /data/src/root/core/unix/src/TUnixSystem.cxx:2118
#3  TUnixSystem::StackTrace (this=0x202e570) at /data/src/root/core/unix/src/TUnixSystem.cxx:2412
#4  0x00007fd8a0f5c24c in TUnixSystem::DispatchSignals (this=0x202e570, sig=kSigSegmentationViolation) at /data/src/root/core/unix/src/TUnixSystem.cxx:3643
#5  <signal handler called>
#6  strlen () at ../sysdeps/x86_64/strlen.S:106
#7  0x00007fd89eb5f140 in PyString_FromString () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#8  0x00007fd89eb8659a in PySys_SetArgvEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#9  0x00007fd8a12d6c0d in ConfigurePython::ConfigurePython(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char**, int) () from /home/bravo/src/hpstr/install/lib/libprocessing.so
#10 0x0000000000401637 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  strlen () at ../sysdeps/x86_64/strlen.S:106
#7  0x00007fd89eb5f140 in PyString_FromString () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#8  0x00007fd89eb8659a in PySys_SetArgvEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#9  0x00007fd8a12d6c0d in ConfigurePython::ConfigurePython(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char**, int) () from /home/bravo/src/hpstr/install/lib/libprocessing.so
#10 0x0000000000401637 in main ()
===========================================================
```

**Comment by mholtrop** [comment]
Hello Cameron,

Thank you for checking!
Two questions:
* Could you please make mcTuple_cfg.py available? 
* Do you have a Python3 on your system, and did cmake use the Python3 to compile hpstr, while root is compiled against Python2?  Could you paste in the cmake output for me please?

**Comment by cbravo135** [comment]
I have placed mcTuple_cfg.py in /volatile/hallb/hps/bravo/move on ifarm at JLab along with a simulation I produced with hps-sim named muonHpsSim.slcio. This is one of the files I use to test things as I develop. 

I do have Python 3 on my system but I am not using it at all in this scenario. I was testing that it was still fully compatible with a pure python 2.7 build.
```
bravo@cbravo-hps:~/src/hpstr/build$ source ../mycmake.sh 
-- LCIO dir set to: /data/src/LCIO/install
-- LCIO include dir set to: /data/src/LCIO/install/include
-- LCIO library set to: /data/src/LCIO/install/lib/liblcio.so
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12") 
-- Python lib found at: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Python include dir found at: /usr/include/python2.7
-- ROOT found at: /data/src/root/buildV61204
-- Adding module: event
-- Adding module: analysis
-- Adding module: processing
-- Adding module: processors
-- hpstr will be installed to: /home/bravo/src/hpstr/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bravo/src/hpstr/build
```

**Review by cbravo135 — APPROVED** [review]
Thanks for keeping python 2.7 as the default python version while making it compatible with both.

**Pull request merged**
